apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: root
  namespace: argocd
spec:
  sourceRepos:
  - https://github.com/kristeey/argo-test-chamber
  destinations:
  - namespace: 'argocd'
    server: '*'
  # Only allow application sets and application projects to be created in this project
  namespaceResourceWhitelist:
  - group: argoproj.io
    kind: ApplicationSet
  - group: argoproj.io
    kind: AppProject