
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: my-helm-app-dev
  namespace: argocd-image-updater-system
spec:
  namespace: argocd  # Where Argo CD Applications are located
  writeBackConfig:
    method: git # "git:secret:argocd-image-updater-system/git-creds"
    gitConfig:
      repository: "git@github.com:kristeey/argo-test-chamber.git"
      branch: "main"
  commonUpdateSettings:
    updateStrategy: digest  # Use digest-based updates
  applicationRefs:
    # Dev
    - namePattern: "my-helm-app-dev"  # Select applications matching this pattern
      labelSelectors:
        matchLabels:
          kristian-app.io/environment: dev
          kristian-app.io/autoImageUpdateEnabled: "true"
      images:
        - alias: "platform-jokes-frontend"  # Alias for the image to be updated
          imageName: "tmpplatformjokesacr-cwbddta9eveuc0gu.azurecr.io/platform-jokes-frontend:dev"
          manifestTargets:
            helm:
              name: "image.name"
              tag: "image.tag"