apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-helm-app
  namespace: argocd
  annotations:
    # Sync Application projects before applying Application Sets
    argocd.argoproj.io/sync-wave: "1"
spec:
  generators:
    - matrix:
        generators:
        # Git Files generator to read values.yaml file in the apps directory
        # This allows dynamic generation of applications based on the values and chart version specified
        - git:
            repoURL: 'https://github.com/kristeey/argo-test-chamber.git'
            revision: main
            files:
              - path: "apps/my-helm-app/*/values.yaml"
            values:
              # Define variables to extract from the file path and content
              # These are used later in the template to set application names and Helm values paths
              ARGOCD_APPLICATION_NAME: '{{index .path.segments 1}}-{{index .path.segments 2}}'
              HELM_VALUES_PATH: '/apps/{{index .path.segments 1}}/{{index .path.segments 2}}/values.yaml'
        - list:
            elements: []
            # Extract required parameters from the argocd section + image.repo in values.yaml
            # These are used in the template and templatePatch sections
            elementsYaml: |
              {{ list (dict 
                "HELM_VERSION" .argocd.HELM_VERSION 
                "AUTO_IMAGE_UPDATE_ENABLED" .argocd.AUTO_IMAGE_UPDATE_ENABLED 
                "AUTO_IMAGE_UPDATE_TAG" .argocd.AUTO_IMAGE_UPDATE_TAG 
                "IMAGE_REPO" .image.repo
              ) | toJson }}
  goTemplate: true
  goTemplateOptions: ['missingkey=error']
  template:
    metadata:
      # Name of the application decided by the app folder and environment folder
      name: '{{ .values.ARGOCD_APPLICATION_NAME }}'
    spec:
      # Source repository - Helm chart with values from the same repo
      source:
        repoURL: 'https://kristeey.github.io/kristian-app-chart'
        chart: kristian-app
        targetRevision: '{{ .HELM_VERSION }}' 
        helm:
          valueFiles:
            - 'https://raw.githubusercontent.com/kristeey/argo-test-chamber/main{{ .values.HELM_VALUES_PATH }}'   
        
      # Destination cluster and namespace to deploy the application
      destination:
        server: https://kubernetes.default.svc # In-cluster deployment
        namespace: '{{ .values.ARGOCD_APPLICATION_NAME }}'
      # Project within ArgoCD to which the application belongs
      project: my-helm-app
      # Sync policy for the application
      # Configures:
      # - automated prune: which will delete resources that are no longer defined in Git
      # - self-heal: which will automatically sync any out-of-sync resources
      # - Auto create namespace: which will create the namespace if it doesn't exist
      # - Server-side apply: which enables server-side apply for resource management
      # - Add custom labels to the managed namespace
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        managedNamespaceMetadata:
          labels:
            app.kubernetes.io/managed-by: argocd-applicationset-controller
            owner: my-helm-app-team
  templatePatch: |
    {{- if eq .AUTO_IMAGE_UPDATE_ENABLED "true" }}
    metadata:
      annotations:
        argocd-image-updater.argoproj.io/image-list: "app={{ .IMAGE_REPO }}:{{ .AUTO_IMAGE_UPDATE_TAG }}"
        argocd-image-updater.argoproj.io/app.helm.image-name: "app.image.repo"
        argocd-image-updater.argoproj.io/app.helm.image-tag: "app.image.tag"
        argocd-image-updater.argoproj.io/app.update-strategy: "digest"
        argocd-image-updater.argoproj.io/git-repository: git@github.com:kristeey/argo-test-chambers.git
        argocd-image-updater.argoproj.io/git-branch: main
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/write-back-target: helmvalues:./values.yaml
        argocd-image-updater.argoproj.io/pull-policy: "IfNotPresent"
    {{- end }}

